[build]
  command = ""
  publish = "public"                  # ← ここ大事
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio","@supabase/supabase-js","web-push"]

# 毎分：通知だけ Netlify で（ファイル名と一致させる）
[[scheduled.functions]]
  name = "notify-dpa-window"
  schedule = "*/1 * * * *"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"



