[build]
  command = ""
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[scheduled.functions]]
  name = "sync-qt"
  cron = "* * * * *"

[[scheduled.functions]]
  name = "ingest-tdr-dpa-background"
  cron = "* * * * *"

[[scheduled.functions]]
  name = "notify-dpa-window"
  cron = "* * * * *"   # 毎分
